language: java
jdk:
- openjdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn test
after_success:
- mvn clean cobertura:cobertura coveralls:report
env:
  global:
    secure: iPE3WhBDDUoyhVQWHNUfSXpd7EH/HAOkC4kMeC+cP2w9/aGA35jmmlcEOoNRKbnuBFpWF51Td1Iq2/19sScSlOmUMR8hYmBcGcy219UraqL88KaM8ToGUKMQStaSvexy5Xv8WO8tEilu5n4vTBM7pQws+8wnQbJWGS4IfXCjpA4kf/5XB8jnHzGuTO/q22g7UpFvHnO3ABlHs1CKf5m0Xmhen9V25Km7G0eYK4kVFMnrylo0snulRAapxfhIwTpNfuJSM8cC+6Sh6znSW18bxhPunMUHdZKcdp7pKVUMC5eKeZbyyUKzbo9PUZg6lsNDDFbRR5Kx6oAS4PVKY4njxST2PtAafQh7qOD6fmy5BBlNDNtsC/aAu2Grz9teB6jzfDNz1UiFlJ5yKgJz3g9N0rsj6W8LJVghhURZDtoV0dwylCjbhEFYY+Jid0CdOZtRdLKEv/3uvddjXbm4KL8OrqaTE8Bpbx3K8oFJhcwWzsEOfLNWW3vnvMaH5SoXVhYQoi88kk9dPtYCaL1AK8d6FBopf6OS6bFHMx+bSPtSdSv2RiaNPwU7zk3HtlZmCgylCWgFFpfiESDDSiVRqBMB2wNpe9+LPEUYEACUvrlbSU2FcC7Wfzkqu6pABx8It7KJxVlo4+AMHzPvhi/Jc72+s/MTCeBlmnkctHmO5BbMOWE=
